import { describe, expect, test } from 'bun:test'
import type { OpenAPIV3_1 } from 'openapi-types'
import {
  generateCrudConfigCode,
  generateCrudConfigTypes,
} from '../generate-crud-config'

// =============================================================================
// Helper
// =============================================================================

const createDocument = (
  doc: Partial<OpenAPIV3_1.Document> = {},
): OpenAPIV3_1.Document =>
  ({
    openapi: '3.1.0',
    info: { title: 'Test API', version: '1.0.0' },
    paths: {},
    ...doc,
  }) as OpenAPIV3_1.Document

const createCrudDocument = (
  name: string,
  fields: Record<string, OpenAPIV3_1.SchemaObject> = {},
  required: string[] = [],
): OpenAPIV3_1.Document =>
  createDocument({
    paths: {
      [`/${name}s/{id}`]: {
        get: {
          operationId: `get${name.charAt(0).toUpperCase()}${name.slice(1)}`,
          tags: [`devup:${name}:one`],
          responses: { '200': { description: 'Success' } },
        },
        put: {
          operationId: `update${name.charAt(0).toUpperCase()}${name.slice(1)}`,
          tags: [`devup:${name}:edit`],
          requestBody: {
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: fields,
                  required,
                },
              },
            },
          },
          responses: { '200': { description: 'Success' } },
        },
        patch: {
          operationId: `patch${name.charAt(0).toUpperCase()}${name.slice(1)}`,
          tags: [`devup:${name}:fix`],
          requestBody: {
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: fields,
                },
              },
            },
          },
          responses: { '200': { description: 'Success' } },
        },
      },
      [`/${name}s`]: {
        post: {
          operationId: `create${name.charAt(0).toUpperCase()}${name.slice(1)}`,
          tags: [`devup:${name}:create`],
          requestBody: {
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: fields,
                  required,
                },
              },
            },
          },
          responses: { '201': { description: 'Created' } },
        },
      },
    },
  })

// =============================================================================
// generateCrudConfigCode - Basic Structure
// =============================================================================

describe('generateCrudConfigCode', () => {
  test('generates header comments and imports', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain(
      '// Auto-generated CRUD components from OpenAPI specs',
    )
    expect(result).toContain('// Do not edit this file directly')
    expect(result).toContain("'use client';")
    expect(result).toContain(
      "import { ApiForm, useFormContext } from '@devup-api/hookform';",
    )
  })

  test('generates component for CRUD group', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain('// UserCrud')
    expect(result).toContain('function UserCrudFields()')
    expect(result).toContain('export function UserCrud(')
  })

  test('generates default export object', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain('export default {')
    expect(result).toContain('user: UserCrud,')
  })

  test('handles multiple CRUD groups', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createDocument({
        paths: {
          '/users/{id}': {
            get: {
              operationId: 'getUser',
              tags: ['devup:user:one'],
              responses: { '200': { description: 'Success' } },
            },
          },
          '/users': {
            post: {
              operationId: 'createUser',
              tags: ['devup:user:create'],
              responses: { '201': { description: 'Created' } },
            },
          },
          '/posts/{id}': {
            get: {
              operationId: 'getPost',
              tags: ['devup:post:one'],
              responses: { '200': { description: 'Success' } },
            },
          },
          '/posts': {
            post: {
              operationId: 'createPost',
              tags: ['devup:post:create'],
              responses: { '201': { description: 'Created' } },
            },
          },
        },
      }),
    })

    expect(result).toContain('UserCrud')
    expect(result).toContain('PostCrud')
    expect(result).toContain('user: UserCrud,')
    expect(result).toContain('post: PostCrud,')
  })

  test('handles empty schemas', () => {
    const result = generateCrudConfigCode({})

    expect(result).toContain("'use client';")
    expect(result).toContain('export default {')
  })

  test('handles documents without valid CRUD configs', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createDocument({
        paths: {
          '/users': {
            get: {
              operationId: 'listUsers',
              tags: ['users'],
              responses: { '200': { description: 'Success' } },
            },
          },
        },
      }),
    })

    expect(result).toContain("'use client';")
    expect(result).toContain('export default {')
    expect(result).not.toContain('function')
  })
})

// =============================================================================
// generateCrudConfigCode - Field Generation
// =============================================================================

describe('generateCrudConfigCode - field generation', () => {
  test('generates text input for string field', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }, [
        'name',
      ]),
    })

    expect(result).toContain('type="text"')
    expect(result).toContain("register('name'")
    expect(result).toContain('<label htmlFor="name">Name</label>')
  })

  test('generates email input for email format', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument(
        'user',
        { email: { type: 'string', format: 'email' } },
        ['email'],
      ),
    })

    expect(result).toContain('type="email"')
  })

  test('generates url input for uri format', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        website: { type: 'string', format: 'uri' },
      }),
    })

    expect(result).toContain('type="url"')
  })

  test('generates url input for url format', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        homepage: { type: 'string', format: 'url' },
      }),
    })

    expect(result).toContain('type="url"')
  })

  test('generates date input for date format', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        birthdate: { type: 'string', format: 'date' },
      }),
    })

    expect(result).toContain('type="date"')
  })

  test('generates datetime-local input for date-time format', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        created_at: { type: 'string', format: 'date-time' },
      }),
    })

    expect(result).toContain('type="datetime-local"')
  })

  test('generates time input for time format', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        start_time: { type: 'string', format: 'time' },
      }),
    })

    expect(result).toContain('type="time"')
  })

  test('generates password input for password format', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        password: { type: 'string', format: 'password' },
      }),
    })

    expect(result).toContain('type="password"')
  })

  test('generates number input for number type', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        score: { type: 'number' },
      }),
    })

    expect(result).toContain('type="number"')
  })

  test('generates number input for integer type', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        age: { type: 'integer' },
      }),
    })

    expect(result).toContain('type="number"')
  })

  test('generates checkbox for boolean type', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        active: { type: 'boolean' },
      }),
    })

    expect(result).toContain('type="checkbox"')
    expect(result).toContain("register('active'")
  })

  test('generates select for enum field', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        status: { type: 'string', enum: ['active', 'inactive', 'pending'] },
      }),
    })

    expect(result).toContain('<select id="status"')
    expect(result).toContain('<option value="">Select...</option>')
    expect(result).toContain('<option value="active">Active</option>')
    expect(result).toContain('<option value="inactive">Inactive</option>')
    expect(result).toContain('<option value="pending">Pending</option>')
  })

  test('generates placeholder from description', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        bio: { type: 'string', description: 'Tell us about yourself' },
      }),
    })

    expect(result).toContain('placeholder="Tell us about yourself"')
  })
})

// =============================================================================
// generateCrudConfigCode - Register Options
// =============================================================================

describe('generateCrudConfigCode - register options', () => {
  test('adds required option for required fields', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }, [
        'name',
      ]),
    })

    expect(result).toContain('required: true')
  })

  test('adds minLength validation', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        name: { type: 'string', minLength: 3 },
      }),
    })

    expect(result).toContain('minLength: 3')
  })

  test('adds maxLength validation', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        name: { type: 'string', maxLength: 100 },
      }),
    })

    expect(result).toContain('maxLength: 100')
  })

  test('adds min validation for numbers', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        age: { type: 'integer', minimum: 18 },
      }),
    })

    expect(result).toContain('min: 18')
  })

  test('adds max validation for numbers', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        age: { type: 'integer', maximum: 120 },
      }),
    })

    expect(result).toContain('max: 120')
  })

  test('adds pattern validation', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        code: { type: 'string', pattern: '^[A-Z]{3}$' },
      }),
    })

    expect(result).toContain('pattern: /^[A-Z]{3}$/')
  })

  test('adds valueAsNumber for number fields', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        score: { type: 'number' },
      }),
    })

    expect(result).toContain('valueAsNumber: true')
  })

  test('adds valueAsNumber for integer fields', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        count: { type: 'integer' },
      }),
    })

    expect(result).toContain('valueAsNumber: true')
  })

  test('combines multiple register options', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument(
        'user',
        {
          name: { type: 'string', minLength: 1, maxLength: 50 },
        },
        ['name'],
      ),
    })

    expect(result).toContain('required: true')
    expect(result).toContain('minLength: 1')
    expect(result).toContain('maxLength: 50')
  })

  test('generates no options for optional field without constraints', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        nickname: { type: 'string' },
      }),
    })

    expect(result).toContain("register('nickname')")
    expect(result).not.toContain("register('nickname', {")
  })
})

// =============================================================================
// generateCrudConfigCode - Component Structure
// =============================================================================

describe('generateCrudConfigCode - component structure', () => {
  test('generates useFormContext hook usage', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain(
      'const { register, formState: { errors } } = useFormContext();',
    )
  })

  test('generates error display for fields', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }, [
        'name',
      ]),
    })

    expect(result).toContain('{errors.name && <span>Required</span>}')
  })

  test('generates Invalid text for optional fields', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        nickname: { type: 'string' },
      }),
    })

    expect(result).toContain('{errors.nickname && <span>Invalid</span>}')
  })

  test('generates submit button', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain('<button type="submit">Submit</button>')
  })

  test('generates ApiForm with correct props', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain('<ApiForm')
    expect(result).toContain('api={apiClient}')
    expect(result).toContain("method={isEdit ? 'put' : 'post'}")
    expect(result).toContain('onSuccess={onSuccess}')
    expect(result).toContain('onError={onError}')
  })

  test('generates fetchDefaultValues for edit mode', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain('fetchDefaultValues={isEdit ? {')
    expect(result).toContain("path: 'getUser',")
    expect(result).toContain('options: { params },')
  })

  test('generates isEdit check', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain('const isEdit = !!params;')
  })

  test('uses edit operationId when available', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain("path={isEdit ? 'updateUser' : 'createUser'}")
  })

  test('uses fix operationId when edit not available', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createDocument({
        paths: {
          '/users/{id}': {
            get: {
              operationId: 'getUser',
              tags: ['devup:user:one'],
              responses: { '200': { description: 'Success' } },
            },
            patch: {
              operationId: 'patchUser',
              tags: ['devup:user:fix'],
              responses: { '200': { description: 'Success' } },
            },
          },
          '/users': {
            post: {
              operationId: 'createUser',
              tags: ['devup:user:create'],
              responses: { '201': { description: 'Created' } },
            },
          },
        },
      }),
    })

    expect(result).toContain("path={isEdit ? 'patchUser' : 'createUser'}")
    expect(result).toContain("method={isEdit ? 'patch' : 'post'}")
  })

  test('generates no fields comment when schema has no properties', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createDocument({
        paths: {
          '/users/{id}': {
            get: {
              operationId: 'getUser',
              tags: ['devup:user:one'],
              responses: { '200': { description: 'Success' } },
            },
          },
          '/users': {
            post: {
              operationId: 'createUser',
              tags: ['devup:user:create'],
              responses: { '201': { description: 'Created' } },
            },
          },
        },
      }),
    })

    expect(result).toContain('{/* No fields defined in OpenAPI schema */}')
  })
})

// =============================================================================
// generateCrudConfigCode - PascalCase and TitleCase conversion
// =============================================================================

describe('generateCrudConfigCode - case conversion', () => {
  test('converts hyphenated names to PascalCase', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createDocument({
        paths: {
          '/user-profiles/{id}': {
            get: {
              operationId: 'getUserProfile',
              tags: ['devup:user-profile:one'],
              responses: { '200': { description: 'Success' } },
            },
          },
          '/user-profiles': {
            post: {
              operationId: 'createUserProfile',
              tags: ['devup:user-profile:create'],
              responses: { '201': { description: 'Created' } },
            },
          },
        },
      }),
    })

    expect(result).toContain('UserProfileCrud')
    expect(result).toContain('UserProfileCrudFields')
  })

  test('converts underscored names to PascalCase', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createDocument({
        paths: {
          '/user_accounts/{id}': {
            get: {
              operationId: 'getUserAccount',
              tags: ['devup:user_account:one'],
              responses: { '200': { description: 'Success' } },
            },
          },
          '/user_accounts': {
            post: {
              operationId: 'createUserAccount',
              tags: ['devup:user_account:create'],
              responses: { '201': { description: 'Created' } },
            },
          },
        },
      }),
    })

    expect(result).toContain('UserAccountCrud')
  })

  test('converts field names to Title Case for labels', () => {
    const result = generateCrudConfigCode({
      'openapi.json': createCrudDocument('user', {
        firstName: { type: 'string' },
        last_name: { type: 'string' },
        'email-address': { type: 'string' },
      }),
    })

    expect(result).toContain('First Name')
    expect(result).toContain('Last Name')
    expect(result).toContain('Email Address')
  })
})

// =============================================================================
// generateCrudConfigTypes
// =============================================================================

describe('generateCrudConfigTypes', () => {
  test('generates module import', () => {
    const result = generateCrudConfigTypes({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain("import '@devup-api/ui'")
  })

  test('generates module augmentation for DevupCrudApiNames', () => {
    const result = generateCrudConfigTypes({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain("declare module '@devup-api/ui' {")
    expect(result).toContain('interface DevupCrudApiNames {')
    expect(result).toContain('user: true')
  })

  test('generates virtual module declaration', () => {
    const result = generateCrudConfigTypes({
      'openapi.json': createCrudDocument('user', { name: { type: 'string' } }),
    })

    expect(result).toContain("declare module '@devup-api/ui/crud' {")
    expect(result).toContain(
      "import type { CrudComponents } from '@devup-api/ui'",
    )
    expect(result).toContain('const crudComponents: CrudComponents')
    expect(result).toContain('export default crudComponents')
  })

  test('includes multiple CRUD groups in type declarations', () => {
    const result = generateCrudConfigTypes({
      'openapi.json': createDocument({
        paths: {
          '/users/{id}': {
            get: {
              operationId: 'getUser',
              tags: ['devup:user:one'],
              responses: { '200': { description: 'Success' } },
            },
          },
          '/users': {
            post: {
              operationId: 'createUser',
              tags: ['devup:user:create'],
              responses: { '201': { description: 'Created' } },
            },
          },
          '/posts/{id}': {
            get: {
              operationId: 'getPost',
              tags: ['devup:post:one'],
              responses: { '200': { description: 'Success' } },
            },
          },
          '/posts': {
            post: {
              operationId: 'createPost',
              tags: ['devup:post:create'],
              responses: { '201': { description: 'Created' } },
            },
          },
        },
      }),
    })

    expect(result).toContain('user: true')
    expect(result).toContain('post: true')
  })

  test('handles empty schemas', () => {
    const result = generateCrudConfigTypes({})

    expect(result).toContain("declare module '@devup-api/ui/crud'")
    expect(result).not.toContain('interface DevupCrudApiNames')
  })

  test('handles documents without valid CRUD configs', () => {
    const result = generateCrudConfigTypes({
      'openapi.json': createDocument({
        paths: {
          '/users': {
            get: {
              operationId: 'listUsers',
              tags: ['users'],
              responses: { '200': { description: 'Success' } },
            },
          },
        },
      }),
    })

    expect(result).not.toContain('interface DevupCrudApiNames')
  })
})
